name: appsyncmasterclass
schema: schema.api.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: us-east-1
  defaultAction: ALLOW
  userPoolId: !Ref CognitoUserPool
additionalAuthenticationProviders:
  - authenticationType: AWS_IAM
mappingTemplatesLocation: mapping-templates
mappingTemplates:
  - type: Subscription
    field: onNotified
    dataSource: none
  - type: Query
    field: getMyProfile
    dataSource: usersTable
  - type: Query
    field: getProfile
    dataSource: usersTable
  - type: Query
    field: getImageUploadURL
    dataSource: getImageUploadUrlFunction
    request: false
    response: false
  - type: Query
    field: getTweets
    dataSource: tweetsTable
  - type: Query
    field: getMyTimeline
    dataSource: timelinesTable
  - type: Query
    field: getLikes
    dataSource: likesTable
  - type: Query
    field: getFollowers
    kind: PIPELINE
    functions:
      - getFollowers
      - hydrateFollowers
    request: simplePipeline.request.vtl
    response: simplePipeline.response.vtl
  - type: Query
    field: getFollowing
    kind: PIPELINE
    functions:
      - getFollowing
      - hydrateFollowing
    request: simplePipeline.request.vtl
    response: simplePipeline.response.vtl
  - type: Query
    field: search
    dataSource: searchFunction
    request: false
    response: false
  - type: Query
    field: getHashTag
    dataSource: getHashTagFunction
    request: false
    response: false
  - type: Query
    field: listConversations
    dataSource: conversationsTable

  - type: Mutation
    field: editMyProfile
    dataSource: usersTable
  - type: Mutation
    field: tweet
    dataSource: tweetFunction
    request: false
    response: false
  - type: Mutation
    field: like
    dataSource: likeMutation
  - type: Mutation
    field: unlike
    dataSource: unlikeMutation
  - type: Mutation
    field: retweet
    dataSource: retweetFunction
    request: false
    response: false
  - type: Mutation
    field: unretweet
    dataSource: unretweetFunction
    request: false
    response: false
  - type: Mutation
    field: reply
    dataSource: replyFunction
    request: false
    response: false
  - type: Mutation
    field: follow
    dataSource: followMutation
  - type: Mutation
    field: unfollow
    dataSource: unfollowMutation
  - type: Mutation
    field: notifyRetweeted
    dataSource: notificationsTable
  - type: Mutation
    field: notifyLiked
    dataSource: notificationsTable
  - type: Mutation
    field: notifyMentioned
    dataSource: notificationsTable
  - type: Mutation
    field: notifyReplied
    dataSource: notificationsTable
  - type: Mutation
    field: sendDirectMessage
    dataSource: sendDirectMessageFunction
    request: false
    response: false

  # Nested fields
  - type: Tweet
    field: profile
    dataSource: usersTable
  - type: Retweet
    field: profile
    dataSource: usersTable
    request: Tweet.profile.request.vtl
    response: Tweet.profile.response.vtl
  - type: Reply
    field: profile
    dataSource: usersTable
    request: Tweet.profile.request.vtl
    response: Tweet.profile.response.vtl
  - type: Retweet
    field: retweetOf
    dataSource: tweetsTable
  - type: Tweet
    field: liked
    dataSource: likesTable
  - type: Tweet
    field: retweeted
    dataSource: retweetsTable
    request: Tweet.liked.request.vtl
    response: Tweet.liked.response.vtl
  - type: Reply
    field: retweeted
    dataSource: retweetsTable
    request: Tweet.liked.request.vtl
    response: Tweet.liked.response.vtl
  - type: OtherProfile
    field: following
    dataSource: relationshipsTable
  - type: OtherProfile
    field: followedBy
    dataSource: relationshipsTable
  - type: Reply
    field: liked
    dataSource: likesTable
    request: Tweet.liked.request.vtl
    response: Tweet.liked.response.vtl
  - type: UnhydratedTweetsPage
    field: tweets
    dataSource: tweetsTable
  - type: MyProfile
    field: tweets
    dataSource: tweetsTable
  - type: OtherProfile
    field: tweets
    dataSource: tweetsTable
    request: MyProfile.tweets.request.vtl
    response: MyProfile.tweets.response.vtl
  - type: Reply
    field: inReplyToTweet
    dataSource: tweetsTable
  - type: Reply
    field: inReplyToUsers
    dataSource: usersTable
  - type: Conversation
    field: otherUser
    dataSource: usersTable

functionConfigurations:
  - name: getFollowers
    dataSource: relationshipsTable
  - name: hydrateFollowers
    dataSource: usersTable
  - name: getFollowing
    dataSource: relationshipsTable
  - name: hydrateFollowing
    dataSource: usersTable
    
dataSources:
  - type: NONE
    name: none
  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: !Ref UsersTable
  - type: AMAZON_DYNAMODB
    name: tweetsTable
    config:
      tableName: !Ref TweetsTable
  - type: AMAZON_DYNAMODB
    name: notificationsTable
    config:
      tableName: !Ref NotificationsTable
  - type: AMAZON_DYNAMODB
    name: conversationsTable
    config:
      tableName: !Ref ConversationsTable
  - type: AMAZON_DYNAMODB
    name: directMessagesTable
    config:
      tableName: !Ref DirectMessagesTable
  - type: AMAZON_DYNAMODB
    name: timelinesTable
    config:
      tableName: !Ref TimelinesTable
  - type: AMAZON_DYNAMODB
    name: likesTable
    config:
      tableName: !Ref LikesTable
  - type: AMAZON_DYNAMODB
    name: retweetsTable
    config:
      tableName: !Ref RetweetsTable
  - type: AMAZON_DYNAMODB
    name: relationshipsTable
    config:
      tableName: !Ref RelationshipsTable
  - type: AMAZON_DYNAMODB
    name: likeMutation
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource: 
            - !GetAtt UsersTable.Arn
            - !GetAtt TweetsTable.Arn
  - type: AMAZON_DYNAMODB
    name: unlikeMutation
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:DeleteItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource: 
            - !GetAtt UsersTable.Arn
            - !GetAtt TweetsTable.Arn
  - type: AMAZON_DYNAMODB
    name: followMutation
    config:
      tableName: !Ref RelationshipsTable
      iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: !GetAtt RelationshipsTable.Arn
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource: !GetAtt UsersTable.Arn
  - type: AMAZON_DYNAMODB
    name: unfollowMutation
    config:
      tableName: !Ref RelationshipsTable
      iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:DeleteItem
          Resource: !GetAtt RelationshipsTable.Arn
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource: !GetAtt UsersTable.Arn
  - type: AWS_LAMBDA
    name: getImageUploadUrlFunction
    config:
      functionName: getImageUploadUrl
  - type: AWS_LAMBDA
    name: tweetFunction
    config:
      functionName: tweet
  - type: AWS_LAMBDA
    name: retweetFunction
    config:
      functionName: retweet
  - type: AWS_LAMBDA
    name: unretweetFunction
    config:
      functionName: unretweet
  - type: AWS_LAMBDA
    name: replyFunction
    config:
      functionName: reply
  - type: AWS_LAMBDA
    name: searchFunction
    config:
      functionName: search
  - type: AWS_LAMBDA
    name: getHashTagFunction
    config:
      functionName: getHashTag
  - type: AWS_LAMBDA
    name: sendDirectMessageFunction
    config:
      functionName: sendDirectMessage

substitutions:
  TweetsTable: !Ref TweetsTable
  LikesTable: !Ref LikesTable
  UsersTable: !Ref UsersTable
  RelationshipsTable: !Ref RelationshipsTable